---
  - name: "Orchestration Example"
    hosts: logicservers
    serial: 1

    tasks:

    - name: "Shutdown Server"
      debug:
        meg: "Shutdown {{ inventory_hostname }}"  

    - name: "Upgrade Firmware"
      debug:
        meg: "Upgrade {{ inventory_hostname }}"  

    - name: "Start Server""
      debug:
        meg: "Start {{ inventory_hostname }}"  